# Generated by Django 3.2.2 on 2022-01-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateTimeField(null=True)),
                ('lesson_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_last_name', models.CharField(max_length=20)),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.discipline')),
                ('topic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.studygroup')),
                ('topic_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOnTheLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.studygroup')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.user')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.topic')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktake.studygroup'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_students',
            field=models.ManyToManyField(through='tasktake.StudentOnTheLesson', to='tasktake.User'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_topics',
            field=models.ManyToManyField(through='tasktake.StudentOnTheLesson', to='tasktake.Topic'),
        ),
    ]
