# Generated by Django 3.2.2 on 2022-01-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
